# docker-compose.yml file version
version: '2'
 
# Data volume for Mongo
volumes:
 pgstorage:

# Services (Docker containers)
services:

  # Postegres Database
  postgresql:
    container_name: gitlab-postgresql
    restart: always
    image: sameersbn/postgresql:9.4-3
    volumes: 
      - pgstorage:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      DB_NAME: gitlabhq_production
      DB_USER: gitlab
      DB_PASS: password

  redis:	  
    container_name: gitlab-redis
    restart: always
    image: sameersbn/redis:latest
    ports:
      - "6379:6379"
    volumes: 
      - glrstorage:/var/lib/redis 
    



