# docker-compose.yml file version
version: '2'
 
# Data volume for Mongo
volumes:
 pgstorage:
 glrstorage:
 gitstorage:

# Services (Docker containers)
services:

  # Postegres Database
  postgresql:
    restart: always
    container_name: gitlab-postgresql
    image: sameersbn/postgresql:9.4-3
    volumes: 
      - pgstorage:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      DB_NAME: gitlabhq_production
      DB_USER: gitlab
      DB_PASS: password

  redis:
    restart: always
    container_name: gitlab-redis
    image: sameersbn/redis:latest
    ports:
      - "6379:6379"
    volumes: 
      - glrstorage:/var/lib/redis 

  gitlab:
    restart: always
    container_name: gitlab
    image: sameersbn/gitlab:7.14.3
    ports:
      - "10080:80"
      - "10022:22"
    depends_on:
      - postgresql
      - redis
    volumes: 
      - gitstorage:/home/git/data 
    environment:
      - GITLAB_PORT: 10080
      - GITLAB_SSH_PORT: 10022
      - DEBUG:false
      - DB_ADAPTER:postgresql
      - DB_HOST:postgresql
      - DB_PORT:5432
      - DB_USER:gitlab
      - DB_PASS:password
      - DB_NAME:gitlabhq_production
      - REDIS_HOST:=redis
      - REDIS_POR:6379
	  